CREATE DATABASE STUDENTRECORD;
USE STUDENTRECORD;

-- CREATE TABLE
CREATE TABLE STUDENTS ( ID INT AUTO_INCREMENT PRIMARY KEY,
                                                    NAME VARCHAR (20),
                                                    AGE INT NOT NULL,
                                                    COURSE VARCHAR (10),
                                                    MARKS INT );
                                                    
INSERT INTO STUDENTS (NAME,AGE,COURSE,MARKS) VALUES ("AMIT",20,"BCA",78);
INSERT INTO STUDENTS (NAME,AGE,COURSE,MARKS) VALUES ("NEHA",21,"BBA",85);
INSERT INTO STUDENTS (NAME,AGE,COURSE,MARKS) VALUES ("RAHUL",19,"BCA",67);
INSERT INTO STUDENTS (NAME,AGE,COURSE,MARKS) VALUES ("PRIYA",22,"BCOM",90);
INSERT INTO STUDENTS (NAME,AGE,COURSE,MARKS) VALUES ("SIMRAN",20,"BBA",72);

-- DISPLAY ALL RECORDS FROM THE TABLE
SELECT * FROM STUDENTS;

-- SHOW ONLY NAME AND MARKS COLUMN
SELECT NAME,MARKS FROM STUDENTS;

-- DISPLAY STUDENTS WHOSE MARKS ARE GREATER THAN 75
SELECT* FROM STUDENTS WHERE MARKS >75;

-- SHOW STUDENTS BELONGING TO BCA COURSE
SELECT * FROM STUDENTS WHERE COURSE = "BCA";

-- DISPLAY STUDENTS WHOSE AGE IS LESS THAN 21
SELECT * FROM STUDENTS WHERE AGE<21;

-- SHOW RECORDS IN ASCENDING ORDER OF MARKS
SELECT*FROM STUDENTS ORDER BY MARKS ASC;

-- DISPLAY THE HIGHEST MARKS OBTAINED BY A  STUDENT
SELECT MAX(MARKS) AS HIGHEST_MARKS FROM STUDENTS;

-- FIND THE AVERAGE MARKS OF ALL STUDENTS
SELECT AVG(MARKS)  AS AVERAGE_MARKS FROM STUDENTS;

-- COUNT TOTAL NUMBER OF STUDENTS
SELECT  COUNT(*) AS TOTAL_STUDENTS FROM STUDENTS;

-- DISPLAY STUDENT NAMES STARTING WITH LETTER "P"
SELECT NAME FROM STUDENTS WHERE NAME LIKE "P%";

-- DISPLAY STUDENTS WHOSE MARKS ARE BETWEEN 70 & 90
SELECT * FROM STUDENTS WHERE MARKS BETWEEN 70 AND 90;

-- SHOW STUDENTS WHOSE COURSE IS EITHER BCA OR BBA
SELECT * FROM STUDENTS WHERE COURSE IN ("BCA","BBA");

-- DISPLAY RECORDS WHERE NAME ENDS WITH LETTER "A"
SELECT * FROM STUDENTS WHERE NAME LIKE "%A";

-- FIND MINIMUM MARKS FROM THE TABLE
SELECT MIN(MARKS) AS MINIMUM_MARKS FROM STUDENTS;

-- DISPLAY TOP 3 STUDENTS BASED ON MARKS
SELECT * FROM STUDENTS ORDER BY MARKS DESC LIMIT 3;

-- COUNT NUMBER OF STUDENTS IN EACH COURSE
SELECT COURSE, COUNT(*) AS TOTAL_STUDENTS FROM STUDENTS GROUP BY COURSE;

-- FIND AVERAGE MARKS COURSEWISE 
SELECT COURSE, AVG(MARKS)  FROM STUDENTS GROUP BY COURSE;

-- DISPLAY STUDENTS WHOSE MARKS ARE NOT EQUAL TO 72
SELECT * FROM STUDENTS WHERE MARKS != 72;

-- SHOW RECORDS SORTED BY AGE IN DESC ORDER
SELECT * FROM STUDENTS ORDER BY AGE DESC;

-- INSERT A NEW STUDENT RECORD INTO THE TABLE
INSERT INTO STUDENTS (NAME,AGE,COURSE,MARKS) VALUES ("TRISHA",20,"BBA",70);

-- UPDATE MARKS OF STUDENT RAHUL TO 75
UPDATE STUDENTS SET MARKS = 75 WHERE NAME = "RAHUL";

-- DELETE RECORD FROM STUDENT WITH ID 3'
DELETE FROM STUDENTS WHERE ID = 3;

-- ADD A NEW COLUMN CITY TO THE TABLE
ALTER TABLE STUDENTS ADD CITY VARCHAR (10);

-- RENAME COLUMN MARKS TO SCORE
ALTER TABLE STUDENTS RENAME COLUMN MARKS TO SCORE;

-- FIND TOTAL SCORE OF ALL STUDENTS
SELECT SUM(SCORE) FROM STUDENTS;

-- DISPLAY MAX AGE OF STUDENTS
SELECT MAX(AGE) FROM STUDENTS;

-- FIND AVERAGE AGE
SELECT AVG(AGE) FROM STUDENTS;

