create database casedemodb;
use casedemodb;
create table productdetails (product_id int primary key,
							product_name varchar(20),
                            Price int not null,
                            price_category varchar(20)
                            );
                            
insert into productdetails (product_id,product_name,price) value (5,"E",0);
SELECT* FROM PRODUCTDETAILS;

-- CASE STATEMENT

SELECT PRODUCT_NAME, PRICE,
CASE
WHEN PRICE<20 THEN "loW"
WHEN PRICE BETWEEN 20 AND 50 THEN "MEDIUM"
WHEN PRICE > 50 THEN "HIGH"
ELSE "NONE"
END AS pRICE_CATEGORY 
FROM PRODUCTDETAILS;

ALTER TABLE PRODUCTDETAILS ADD PAYMENT_STATUS VARCHAR (10);
ALTER TABLE PRODUCTDETAILS ADD CODE INT NOT NULL;
UPDATE PRODUCTDETAILS SET PAYMENT_STATUS = "PROCESSING" WHERE PRODUCT_ID = 4; 
SELECT PRODUCT_NAME, PRICE, PAYMENT_STATUS,
CASE
WHEN PAYMENT_STATUS = "PENDING" THEN 1
WHEN PAYMENT_STATUS = "PROCESSING" THEN 2
WHEN PAYMENT_STATUS = "COMPLETED" THEN 3

END AS PAYMENT_STATUS 
FROM PRODUCTDETAILS;

SELECT * ,
CASE PAYMENT_STATUS
WHEN PAYMENT_STATUS = "PENDING" THEN 1
WHEN PAYMENT_STATUS = "PROCESSING" THEN 2
WHEN PAYMENT_STATUS = "COMPLETED" THEN 3
ELSE 4
END AS CODE
FROM PRODUCTDETAILS
ORDER BY CODE;
